Support latest version of rest-client
envoy/eventbrite pull request #24
Opened 2017-08-24 11:38 UTC by apuntovanini

This commit fixes #16, tested in my environment and seems to be working fine

2017-10-11 06:20 UTC, apuntovanini commented
@envoy any plans to merge it?

2017-10-11 17:23 UTC, kamal requested changes

2017-10-11 17:23 UTC, kamal commented on eventbrite.gemspec
> +  spec.add_dependency "rest-client", ">= 1.4"
I would prefer this change to be `~> 2.0`

2017-10-11 17:24 UTC, kamal commented
@apuntovanini thanks for the PR! Just left one small comment.

2017-10-11 20:15 UTC, apuntovanini commented
@kamal here it is, you're definitely right. Updated PR, guess it's ready to be merged. Will you release a new version with the latest changes? Thanks for maintaining this!

2017-10-11 20:30 UTC, merged

2017-10-11 20:30 UTC, kamal commented
@apuntovanini thanks! i'll cut a release in a couple hours

2017-10-19 19:03 UTC, apuntovanini commented
@kamal I think you forgot to cut the release! :)

2018-01-19 00:37 UTC, kamal commented
@apuntovanini i finally got ownership of the repo and pushed the latest release. Sorry for the delay!